#!/usr/bin/env bash

# config
BRANCHES=("prod" "staging")
PROJECT_PREFIX="cc-"
WORK_TREE_DIR="/home/git/worktrees"

while read oldrev newrev ref; do
  branch=`echo $ref | rev | cut -d / -f 1 | rev`
  if [[ " ${BRANCHES[*]} " =~ " $branch " ]]; then
    echo "Ref $ref received. Deploying [$branch]..."

    # check out to worktree
    mkdir -p "$WORK_TREE_DIR/services"
    GIT_WORK_TREE="$WORK_TREE_DIR/services" git checkout -f $branch
    cd "$WORK_TREE_DIR/services"

    # update status
    echo `jq \
      --arg commit "$(git rev-parse HEAD | head -c 7)" \
      --arg timestamp "$(date --iso-8601=ns | cut -d, -f 1)" \
      --arg environment "$branch" \
      '.commit = $commit | .timestamp = $timestamp | .environment = $environment' \
      static/json/status.json` > static/json/status.json

    # configure local submodule repos
    sed -i "s/github.com:Clubs-Council-IIITH\//clubs.iiit.ac.in:/g" .gitmodules
    git submodule add -b $branch git@clubs.iiit.ac.in:services.git
    rm services/.gitmodules

    # pull submodules (except auth-dev)
    git -c submodule.auth-dev.update=none submodule update --init --recursive

    # update changelog
    git submodule foreach \
      'git log --no-merges --oneline --date=short --pretty=format:"**%ad:** [$name] %s  " | cat && echo' \
      | grep -v ^Entering | sort -r -o static/mdx/logs.mdx

    # deploy new images
    docker compose -f docker-compose.$branch.yml -p $PROJECT_PREFIX$branch up -d

    # verify build status
    if [ $? -ne 0 ]; then
      echo "Build failed! Aborting."
      exit 1
    fi

    # clean up worktree
    git checkout .
    rm -rf ./services

    echo "Deployed [$branch] successfully!"
  else
    echo "Ref $ref received. Doing nothing: only [${BRANCHES[*]}] may be deployed on this server."
  fi
done

